name: release-tag
on:
  push:
    branches:
      - main
env:
  NODE_VERSION: 18.17.1 # 和项目中的pnpm版本一致
  PNPM_VERSION: 8.6.12 # 和项目中的node版本一致

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出仓库代码
        uses: actions/checkout@v3
      - name: 安装pnpm
        uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: 设置node环境
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'pnpm'
      - name: 安装依赖
        run: pnpm install
      - name: 构建打包
        run: pnpm docs:build
      - name: 配置ossutil
        uses: manyuanrong/setup-ossutil@v2.0
        with:
          endpoint: oss-cn-hangzhou.aliyuncs.com
          access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.ACCESS_KEY_SECRET }}
      - name: 上传到阿里云OSS
        run: ossutil cp -rf dist oss://tingkelai-front/tingkelai/help/
